### ISSUE TITLE
missing tables in uvfits file created using ms.tofits

### ISSUE THREAD

**Issue by astrosumit** [casacore/casacore#1013]
Hi,
I was trying to convert a uvfits file downloaded from astrogeo.org website into a measurement set. I want to perform some analysis using casacore tools and then convert back to uvfits file for further analysis using DIFMAP. The following is my piece of code:
import os,sys
import shutil
from casac import casac

datafile='J0003-1727_X_2018_08_14_pet_vis.fits'

ms=casac.ms()

cwd = os.getcwd()
if os.path.exists('raw_uvdata.ms'):
    shutil.rmtree(os.path.join(cwd, 'rawuvdata.ms'))

ms.fromfits(msfile='raw_uvdata.ms', fitsfile=datafile) 

ms.open('raw_uvdata.ms')
ms.tofits('modified_uvdata.fits', column='data', multisource=False, combinespw=True, writestation=True, padwithflags=True, overwrite=True)
ms.done()

When I load this modified_uvdata.fits file in DIFMAP, it says:
$ difmap
0>obs  modified_uvdata.fits 
Reading UV FITS file: modified_uvdata.fits
loc_base: Missing AN table, version: 3
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.
Segmentation fault (core dumped)

**Comment by tammojan** [comment]
This is likely related to #1005. This was fixed only in the very latest release (released minutes ago in fact), so you probably were using a version without the fix. Could you try upgrading?

**Comment by astrosumit** [comment]
I updated the casacore with the command:
$ conda update python-casacore pwkit casa-tools casa-python casa-data 

But still the same problem.

**Comment by tammojan** [comment]
> I updated the casacore with the command:
> $ conda update python-casacore pwkit casa-tools casa-python casa-data
> 
> But still the same problem.

Thanks for testing; however yesterday's release has not made it to conda yet. We are working on a new python-casacore and will keep you posted.

**Comment by tammojan** [comment]
Keep an eye on conda-forge/python-casacore-feedstock#16, once that gets merged you may be able to update conda and get the latest casacore.

**Comment by astrosumit** [comment]
I installed CASA-6 and tried a similar program as with casac module. I got the same problem of missing AN table version 3 while using DIFMAP. I tested my programs on other uvfits files from astrogeo.org and I found the program works fine for the uvfits file having only one AN table and the problem occurs only for uvfitls file having more than one AN table versions. Any help on this would be appreciated.

**Comment by tammojan** [comment]
You'll have to install casacore 3.3.0 and python-casacore 3.3.0 somehow (e.g. with conda) to get the changes. CASA-6 does not ship the fix yet.

**Comment by gijzelaerr** [comment]
@astrosumit this has been a while ago, did you manage to get a recent casacore working to verify your issue has been solved?
